services:
  nest-app:
    build: ./goods-app-backend
    ports:
      - "${NEST_APP_PORT}:3000"
    volumes:
      - ./goods-app-backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  frontend:
    build: ./goods-app-frontend
    ports:
      - "${NEXT_APP_PORT}:3000"
    volumes:
      - ./goods-app-frontend:/app
    depends_on:
      - nest-app
    environment:
      - NEXT_PUBLIC_NEST_API_ADDRESS=http://localhost:${NEST_APP_PORT}

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:3306"
    restart: always

volumes:
  db-data: